PDTPLeilaoServer/PDTPLeilaoServer-war/src/java/pt/pd/leilao/server/faces/NewsletterManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.pd.leilao.server.faces;

import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import pt.pd.leilao.server.model.NewsletterMessageEntity;
import pt.pd.leilao.server.services.singletons.NewsletterManagerSingletonLocal;

/**
 *
 * @author dfortunato
 */
@ManagedBean(name = "newsletterManagedBean")
@RequestScoped
public class NewsletterManagedBean {

    @EJB
    public NewsletterManagerSingletonLocal newsletterManagerSingletonLocal;
    
    /**
     * Creates a new instance of NewsletterManagedBean
     */
    public NewsletterManagedBean() {
    }
    
    public String getHelloNewsletter()
    {
        return "Mensagem a partir de " + NewsletterManagedBean.class.getName();
    }
    
    public String getListNewsletter()
    {
        StringBuilder strBuilder = new StringBuilder();
        strBuilder.append("****************");
        
        for(NewsletterMessageEntity newsletterMessageEntity : newsletterManagerSingletonLocal.getListNewsletter())
        {
            strBuilder.append("\n").append(newsletterMessageEntity.generateListLineDescription());
        }
        strBuilder.append("****************");
        
        return strBuilder.toString();
    }
    
}

PDTPLeilaoServer/PDTPLeilaoServer-war/web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets.
        <p>#{newsletterManagedBean.helloNewsletter}</p>
        <p>Newsletter: #{newsletterManagedBean.listNewsletter}</p>
    </h:body>
</html>