PDTPLeilaoWebApp/src/java/pt/pd/leilao/server/services/controllers/ItemDetailsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.pd.leilao.server.services.controllers;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import pt.pd.leilao.server.model.ItemBidEntity;
import pt.pd.leilao.server.model.ItemEntity;
import pt.pd.leilao.server.model.ResponseService;
import pt.pd.leilao.server.services.ClientItemsServiceRemote;
import pt.pd.leilao.server.services.utils.AlertMessagesUtil;

/**
 *
 * @author dfortunato
 */
@Named(value = "itemDetailsController")
@RequestScoped
public class ItemDetailsController implements Serializable{

    @Inject
    private UserController userController;
    
    @EJB
    private ClientItemsServiceRemote clientItemsServiceRemote;
        
    private int itemId = -1;
    
    
    /**
     * Creates a new instance of ItemDetailsController
     */
    public ItemDetailsController() {
    }
    
    public ItemEntity getItemDetails()
    {
        if (itemId == -1) {
            Map<String,String> mapParams = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
            String id = mapParams.get("id");
            itemId = Integer.valueOf(id);
        }
        return clientItemsServiceRemote.findItemEntityById(itemId).getDataObject();
    }
    
    public boolean isAllowedToBuy()
    {
        return userController.isAllowedToBuyItem(getItemDetails());
    }
    
    public boolean isAllowedToBuyNow()
    {
        return userController.isAllowedToBuyItem(getItemDetails()) && getItemDetails().isBuyNowAllowed();
    }

    public void setUserController(UserController userController) {
        this.userController = userController;
    }
    
    public String getFollowButtonTitle()
    {
        if (userController.isFollowingItem(getItemDetails().getId())) 
        {
            return "Deixar de seguir";
        }
        else
        {
            return "Seguir item";
        }
    }
    
    public void toggleFollowingItem()
    {
        userController.toggleFollowItem(getItemDetails().getId());
    }
    
    public void sendMessageToSeller()
    {
        Map<String,String> mapParams = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String message = mapParams.get("form_item_details:form_input_text:item_text_area");
        userController.sendMessageToSeller(message, getItemDetails());
    }
    
    public void reportUserSeller()
    {
        Map<String,String> mapParams = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String message = mapParams.get("form_item_details:form_input_text:item_text_area");
        userController.reportSellerAbuse(message, getItemDetails());
    }
    
    public void reportItemSeller()
    {
        Map<String,String> mapParams = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String message = mapParams.get("form_item_details:form_input_text:item_text_area");
        userController.reportItemAbuse(message, getItemDetails());
    }
    
    public void buyNowItem()
    {
        ResponseService responseService = userController.buyItem(getItemDetails().getId(), getItemDetails().getBuyNowPrice());
        
        if (responseService.isSuccess()) 
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "O item foi adquirido com sucesso!");
        }
        else
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "Não foi possivel adquirir o item");
        }
    }
    
    public String putNewItemBid()
    {
        String valueBid = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("in_licitacao");
        
        ResponseService responseService = userController.buyItem(getItemDetails().getId(), Float.valueOf(valueBid));
        
        if (responseService.isSuccess()) 
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "A sua licitacao foi feita com sucesso");
        }
        else
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "Não foi possivel licitar o item");
        }
        
        return null;
    }
    
    public List<ItemBidEntity> getListItemBids()
    {
        List<ItemBidEntity> listBids = clientItemsServiceRemote.getListItemBids(itemId);
        
        return listBids;
    }
    
}

PDTPLeilaoWebApp/src/java/pt/pd/leilao/server/services/controllers/NewsletterController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.pd.leilao.server.services.controllers;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.bean.ManagedBean;
import pt.pd.leilao.server.model.NewsletterMessageEntity;
import pt.pd.leilao.server.services.ClientNewsletterServiceRemote;
import pt.pd.leilao.server.services.singletons.NewsletterManagerSingletonLocal;

/**
 *
 * @author dfortunato
 */
@ManagedBean(name = "newsletterController")
@RequestScoped
public class NewsletterController implements Serializable {

    @EJB
    ClientNewsletterServiceRemote clientNewsletterServiceRemote;
    
    /**
     * Creates a new instance of NewsletterController
     */
    public NewsletterController() {
    }
    
    public String getTestMessage()
    {
        return "This message is a test from " + NewsletterController.class.getSimpleName();
    }
    
    public List<NewsletterMessageEntity> getListNewsletter()
    {
        return clientNewsletterServiceRemote.getListNewsletters();
    }
    
}

PDTPLeilaoWebApp/src/java/pt/pd/leilao/server/services/controllers/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.pd.leilao.server.services.controllers;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import org.jboss.logging.Logger;
import pt.pd.leilao.server.model.CategoryEntity;
import pt.pd.leilao.server.model.ItemEntity;
import pt.pd.leilao.server.model.ResponseService;
import pt.pd.leilao.server.model.UserEntity;
import pt.pd.leilao.server.model.UserMessageEntity;
import pt.pd.leilao.server.model.UserNotificationEntity;
import pt.pd.leilao.server.model.enums.ItemStateType;
import pt.pd.leilao.server.model.enums.UserType;
import pt.pd.leilao.server.model.enums.responses.ResponseUserLoginType;
import pt.pd.leilao.server.model.enums.responses.ResponseUserRegisterType;
import pt.pd.leilao.server.model.responses.ResponseUserLoginData;
import pt.pd.leilao.server.services.ClientItemsServiceRemote;
import pt.pd.leilao.server.services.ClientUserService;
import pt.pd.leilao.server.services.ClientUserServiceRemote;
import pt.pd.leilao.server.services.controllers.types.ListItemsType;
import pt.pd.leilao.server.services.utils.AlertMessagesUtil;
import pt.pd.leilao.server.services.utils.Utils;

/**
 *
 * @author dfortunato
 */
@Named(value = "userController")
@SessionScoped
public class UserController implements Serializable {
    private static final String TAG = UserController.class.getSimpleName();
    
    @EJB
    ClientUserServiceRemote clientUserServiceRemote;
    
    @EJB
    ClientItemsServiceRemote clientItemsServiceRemote;
    
    /**
     * Creates a new instance of UserController
     */
    public UserController() {
        Logger.getLogger(TAG).debug("Constructor new UserController");
    }
    
    public String loginUser()
    {
        // Get Data
        Map params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String username = (String) params.get("in_username");
        String password = (String) params.get("in_password");
        
        ResponseUserLoginData responseUserLoginData = clientUserServiceRemote.loginUser(username, password);
        
        // Handle response
        FacesContext context = FacesContext.getCurrentInstance();
        switch(responseUserLoginData.getResponseUserLoginType())
        {
            case LOGIN_SUCCESS:
                return getInitialScreen();
            case ALREADY_LOGGED_IN:
                AlertMessagesUtil.displayResponseMessage("O utilizar já se encontra logado");
                break;
            case FAILED_NOT_ACTIVE:
                AlertMessagesUtil.displayResponseMessage("O utilizador não está activo");
                break;
            case FAILED_PASSWORD_WRONG:
                AlertMessagesUtil.displayResponseMessage("Password incorrecta");
                break;
            case FAILED_USERNAME_NOT_FOUND:
                AlertMessagesUtil.displayResponseMessage("O username não existe");
                break;
        }

        return null;
    }
    
    public String updateUser()
    {
        // Get Data
        Map params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String name = (String) params.get("input_nome");
        String morada = (String) params.get("input_morada");
        UserEntity updatedEntity = new UserEntity();
        updatedEntity.setNome(name);
        updatedEntity.setMorada(morada);
        
        ResponseService responseService = clientUserServiceRemote.updateUserData(updatedEntity);
        if (responseService.isSuccess()) 
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "Dados actualizados com sucesso");
        }
        else
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "Algo falhou na actualização dos dados");
        }
        return "user_manage_account_menu";
    }
    
    /**
     * Post a Suspension order
     * @return 
     */
    public String postSuspensionOrder()
    {
        // Get Data
        Map params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String motivo = (String) params.get("ta_motivo");
        
        ResponseService responseService = clientUserServiceRemote.suspendUser(motivo);
        
        if (responseService.isSuccess()) 
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "Pedido de suspensão enviado com sucesso");
            return "user_manage_account_menu";
        }
        else
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "Falhou o pedido de suspensao");
            return null;
        }
    }
    
    
    public String changePassword()
    {
        // Get Data
        Map params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String passwordOld = (String) params.get("input_password_antiga");
        String passwordNew = (String) params.get("input_password_nova");
        
        ResponseService responseService = clientUserServiceRemote.changePassword(passwordOld, passwordNew);
        
        if (responseService.isSuccess()) 
        {
            AlertMessagesUtil.displayResponseMessage(responseService, "A alteração foi efectuada com sucesso!");
            switch(clientUserServiceRemote.getCurrentUser().getUserType())
            {
                case ADMIN:
                    return "admin_user_menu";
                case REGISTERED:
                    return "user_manage_account_menu";
            }
        }
        else
        {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Não foi possivel alterar a sua password - Codigo de erro: " + responseService.getResponseMessage()));
        }
        return null;
    }
    
    public String registerUser()
    {
        // Get Data
        Map params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String username = (String) params.get("in_username");
        String password = (String) params.get("in_password");
        
        UserEntity userEntity = new UserEntity();
        userEntity.setUserName(username);
        userEntity.setPassword(password);
        
        ResponseUserRegisterType responseUserRegisterType = clientUserServiceRemote.registerUser(userEntity);
        
        // Handle Response
        FacesContext context = FacesContext.getCurrentInstance();
        switch(responseUserRegisterType)
        {
            case USER_REGISTERED:
                AlertMessagesUtil.displayResponseMessage("Utilizador Registado com sucesso");
                return "index";
            case USER_REGISTER_PENDING_APPROVAL:
                AlertMessagesUtil.displayResponseMessage("Utilizador Registado. Está pendente de aprovação");
                return "index";
            case USERDATA_NOT_VALID:
                AlertMessagesUtil.displayResponseMessage("Dados de registo inválidos");
                break;
            case USERNAME_ALREADY_EXISTS:
                AlertMessagesUtil.displayResponseMessage("O nome de utilizador que tentou registar já existe");
                break;
        }
        
        return null;
    }
    
    public String validateUserRegisteredAccess()
    {
        if (isLoggedIn() && getCurrentUser().getUserType() == UserType.REGISTERED || getCurrentUser().getUserType() == UserType.ADMIN) 
        {
            return null;
        }
        else
        {
            // Send it to login
            return "init_login_user";
        }
    }
    
    public String validateUserAdminAccess()
    {
        if (isLoggedIn() && getCurrentUser().getUserType() == UserType.ADMIN) 
        {
            return null;
        }
        else
        {
            // Send it to login
            return "init_login_user";
        }
    }
    
    public void depositMoney()
    {
        // Get Data
        Map params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String depositMoney = (String) params.get("input_money");
        
        try
        {
          ResponseService responseService = clientUserServiceRemote.transferMoney(Float.parseFloat(depositMoney));
            if (responseService.isSuccess()) 
            {
                AlertMessagesUtil.displayResponseMessage(responseService, "Foram depositados " + depositMoney + "€ com sucesso");
            }
            else
            {
                AlertMessagesUtil.displayResponseMessage(responseService, "Não foi possivel transferir dinheiro para a sua conta");
            }  
        } catch(NumberFormatException e)
        {
            AlertMessagesUtil.displayResponseMessage("Não foi possivel transferir dinheiro para a sua conta. Tem de inserir um valor numérico válido.");
        }
        
    }
    
    public String logout()
    {
        return clientUserServiceRemote.logout() ? "index" : null;
    }
    
    public String getWelcomeMessage()
    {
        switch(getCurrentUser().getUserType())
        {
            case ADMIN:
                return "Bem vindo administrador. ";
            case REGISTERED:
                return "Bem vindo " + getCurrentUser().getUserName();
            case GUEST:
                return "Bem vindo visitante.";
        }
        return "";
    }
    
    public UserEntity getCurrentUser()
    {
        return clientUserServiceRemote.getCurrentUser();
    }
    
    public boolean changePassword(String oldPassword, String newPassword)
    {

PDTPLeilaoWebApp/web/admin_manage_report_items_list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./leilao_template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:p="http://primefaces.org/ui">

    <ui:define name="top">
        Gerir lista de denuncias de items
    </ui:define>

    <ui:define name="content">
        <h:form>
            <p:poll interval="10" update="@form"/>
            <h:dataTable value="#{adminController.listItemReports}"
                     var="report"
                     border="0"
                     cellpadding="2"
                     cellspacing="0"
                     rowClasses="linhas_impares,linhas_pares"
                     rules="all"
                     style="border:solid 1px"
                     >
                <!-- ID -->
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="ID"/>
                    </f:facet>
                    <h:outputText value="#{report.id}"/>
                </h:column>
                <!-- User Reporter -->
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Denunciado por"/>
                    </f:facet>
                    <h:outputText value="#{report.idUserSentReport.userName}"/>
                </h:column>
                <!-- Item Target -->
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Item denunciado"/>
                    </f:facet>
                    <h:outputText value="#{report.idItemTarget.description}"/>
                </h:column>
                <!-- Vendedor do item -->
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Vendedor do item"/>
                    </f:facet>
                    <h:outputText value="#{report.idItemTarget.userSeller.userName}"/>
                </h:column>
                <!-- Motivo -->
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Motivo:"/>
                    </f:facet>
                    <h:outputText value="#{report.message}"/>
                </h:column>
                <!-- Resposta -->
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Resposta:"/>
                    </f:facet>
                    <h:commandButton value="Aprovar" action="#{adminController.replyReportItem()}" style="margin-right: 5px">
                        <f:param name="reportId" value="#{report.id}" />
                        <f:param name="newReportState" value="accepted" />
                        <f:ajax render="@form" execute="@form"/>
                    </h:commandButton>
                    <h:commandButton value="Rejeitar" action="#{adminController.replyReportItem()}" style="margin-right: 5px">
                        <f:param name="reportId" value="#{report.id}" />
                        <f:param name="newReportState" value="rejected" />
                        <f:ajax render="@form" execute="@form"/>
                    </h:commandButton>
                </h:column>
            </h:dataTable>
            <hr/>
            <h:link outcome="admin_user_menu" value="Voltar"/>
            <br/>
        </h:form>
    </ui:define>

    <ui:define name="bottom">
    </ui:define>

</ui:composition>

PDTPLeilaoWebApp/web/guest_menu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./leilao_template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns="http://www.w3.org/1999/xhtml">

    <ui:define name="top">
        Bem vindo Visitante
    </ui:define>

    <ui:define name="content">
        <h:form>
            <h:link value="Pedir Reactivação de conta" outcome="guest_insert_reactivate_order"/>
            <br/>
            <h:link value="Listar Ultimos Artigos" outcome="guest_list_last_sold_items" /> 
            <br/>
            <h:link value="Visualizar Newsletter" outcome="newsletter"/>
            <br/>
            <h:link value="Voltar" outcome="index"/>
        </h:form>
    </ui:define>

    <ui:define name="bottom">
    </ui:define>

</ui:composition>

PDTPLeilaoWebApp/web/init_register_new_user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./leilao_template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns="http://www.w3.org/1999/xhtml">

    <ui:define name="top">
        Registar Novo Utilizador
    </ui:define>

    <ui:define name="content">
        
        <h:form rendered="#{userController.loggedIn}">
            <h:panelGrid columns = "2" >
                <h:outputText value="User logado" />
                <h:outputText value="#{userController.currentUser.userName}" />
                <h:commandButton action="#{userController.logout()}"
                               value="Logout" >
                </h:commandButton>
            </h:panelGrid>
        </h:form>
        
        <h:form rendered="#{userController.loggedIn eq false}">
            Insere os dados do utilizador:
            <br/>
            <br/>
            <p>Username: <input id="username" name="in_username" required="true" requiredMessage="Escreve o username" /></p>
            <p>Password: <input id="password" name="in_password" required="true" requiredMessage="Escreve a password" type="password"/></p>
            <p>
                <h:commandButton action="#{userController.registerUser()}"
                           value="Registar utilizador" />
            </p>

        </h:form>
        
    </ui:define>

    <ui:define name="bottom">
    </ui:define>

</ui:composition>

PDTPLeilaoWebApp/web/leilao_template.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
  
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css"/>
        <h:outputStylesheet library="css" name="cssLayout.css"/>
        <h:outputStylesheet library="css" name="cssbasico.css" />
        <title>PD Leilao</title>
    </h:head>

    <h:body>        
        <div id="top">   
            <h:form>
                <p:poll interval="1" update="@form"/>
                <h:outputLabel value="#{userController.welcomeMessage} Hora actual: #{userController.currentTime}" />
            </h:form>
            <ui:insert name="top"></ui:insert>
        </div>

        <div id="content" class="center_content">
            <h:form>
                <p:growl id="growl" showDetail="true" life="3000" />
            </h:form>
            <ui:insert name="content"></ui:insert>
        </div>

        <div id="bottom">
            <ui:insert name="bottom"></ui:insert>
            <!-- Menu Registered -->
            <h:form rendered="#{userController.currentUser.userType.typeValue eq 'registered'}">
                <p:poll interval="10" update="@form"/>
                
                <h:link value="Inicio" outcome="registered_user_menu" style="margin-right: 5px"/>
                |
                <h:link value="Gerir Conta" outcome="user_manage_account_menu" style="margin-right: 5px"/>
                |
                <h:link value="Gerir Items" outcome="user_items_menu" style="margin-right: 5px"/>
                |
                <h:link value="Gerir Mensagens" outcome="user_messages_menu" style="margin-right: 5px"/>
                |
                <h:link value="Pesquisar Items" outcome="user_search_items_list" style="margin-right: 5px"/>
                |
                <h:link value="Visualizar Newsletter" outcome="newsletter" style="margin-right: 5px"/>
                |
                <h:commandButton value="Logout" action="#{userController.logout()}"/>
                <hr/>
                <br/>
                Ultimas notificações:
                <br/>
                <h:dataTable value="#{userController.lastNotifications}"
                     var="notification"
                     border="0"
                     cellpadding="2"
                     cellspacing="0"
                     rowClasses="linhas_impares,linhas_pares"
                     rules="all"
                     style="border:solid 1px"
                     >
                    <!-- ID -->
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="ID"/>
                        </f:facet>
                        <h:outputText value="#{notification.id}"/>
                    </h:column>
                    <!-- Message -->
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Mensagem"/>
                        </f:facet>
                        <h:outputText value="#{notification.message}"/>
                    </h:column>
                    <!-- Date -->
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Data de envio"/>
                        </f:facet>
                        <h:outputText value="#{notification.dateSendFormatted}"/>
                    </h:column>
                </h:dataTable>
                
            </h:form>
            
            <!-- Menu Admin -->
            <h:form rendered="#{userController.currentUser.userType.typeValue eq 'admin'}">
                <h:link value="Inicio" outcome="admin_user_menu" style="margin-right: 5px"/>
                |
                <h:link value="Gerir pedidos de activação e suspensão" outcome="admin_manage_user_requests" style="margin-right: 5px"/>
                |
                <h:link value="Gerir Items" outcome="admin_manage_item_list" style="margin-right: 5px"/>
                |
                <h:link value="Gerir Categorias" outcome="admin_manage_categories_list" style="margin-right: 5px"/>
                |
                <h:link value="Gerir Utilizadores" outcome="admin_manage_users" style="margin-right: 5px"/>
                |
                <h:link value="Gerir Mensagens" outcome="user_messages_menu" style="margin-right: 5px"/>
                |
                <h:link value="Alterar password" outcome="user_edit_password_form" style="margin-right: 5px"/>
                |
                <h:link value="Newsletter" outcome="newsletter" style="margin-right: 5px"/>
                |
                <h:commandButton value="Logout" action="#{userController.logout()}"/>
            </h:form>
            
            <!-- Menu Guest -->
            <h:form rendered="#{userController.currentUser.userType.typeValue eq 'guest'}">
                <h:link value="Inicio" outcome="index" style="margin-right: 5px"/>
                |
                <h:link value="Pedir Reactivação de conta" outcome="guest_insert_reactivate_order" style="margin-right: 5px"/>
                |
                <h:link value="Listar Ultimos Artigos" outcome="guest_list_last_sold_items" style="margin-right: 5px" /> 
                |
                <h:link value="Visualizar Newsletter" outcome="newsletter"/>
            </h:form>
        </div>

    </h:body>

</html>

PDTPLeilaoWebApp/web/user_edit_profile_form.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./leilao_template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns="http://www.w3.org/1999/xhtml">

    <f:metadata xmlns:f="http://xmlns.jcp.org/jsf/core">
        <f:viewAction action="#{userController.validateUserRegisteredAccess}" />
    </f:metadata>
    
    <ui:define name="top">
        Editar Perfil
    </ui:define>

    <ui:define name="content">
        <h:form>
            <label>Nome: </label>
            <input id="in_nome" name="input_nome" value="#{userController.currentUser.nome}"/>
            <br/>
            <label>Morada: </label>
            <input id="in_morada" name="input_morada" value="#{userController.currentUser.morada}"/>
            <br/> 
            <p>
                <h:link outcome="user_manage_account_menu" value="Cancelar" style="margin-right: 20px;"/>
                <h:commandButton action="#{userController.updateUser()}"
                           value="Actualizar dados" />
            </p>
            
        </h:form>
    </ui:define>

    <ui:define name="bottom">
    </ui:define>

</ui:composition>